# Generated by Django 3.2.8 on 2021-11-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0003_auto_20211115_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='canidatestatus',
            name='accounts_status',
            field=models.CharField(max_length=132, null=True),
        ),
        migrations.AlterField(
            model_name='canidatestatus',
            name='accounts',
            field=models.CharField(max_length=132, null=True),
        ),
        migrations.AlterField(
            model_name='canidatestatus',
            name='hr_FeedBack',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='canidatestatus',
            name='hr_Status',
            field=models.CharField(max_length=132, null=True),
        ),
        migrations.AlterField(
            model_name='canidatestatus',
            name='team_lead_feedback',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='canidatestatus',
            name='team_lead_status',
            field=models.CharField(max_length=132, null=True),
        ),
    ]
