# Generated by Django 3.2.8 on 2021-11-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0004_auto_20211115_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsCanidateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts', models.CharField(max_length=132, null=True)),
                ('accounts_status', models.CharField(max_length=132, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HRCanidateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_Status', models.CharField(max_length=132, null=True)),
                ('hr_FeedBack', models.CharField(max_length=300, null=True)),
                ('JobApplication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Applications.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='TMCanidateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_lead_status', models.CharField(max_length=132, null=True)),
                ('team_lead_feedback', models.CharField(max_length=300, null=True)),
                ('JobApplication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Applications.hrcanidatestatus')),
            ],
        ),
        migrations.DeleteModel(
            name='CanidateStatus',
        ),
        migrations.AddField(
            model_name='accountscanidatestatus',
            name='JobApplication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Applications.tmcanidatestatus'),
        ),
    ]
