# Generated by Django 3.2.8 on 2021-11-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0005_auto_20211115_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountscanidatestatus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hrcanidatestatus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tmcanidatestatus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
