# Generated by Django 3.2.8 on 2021-11-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0006_auto_20211115_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountscanidatestatus',
            old_name='accounts',
            new_name='accounts_feedback',
        ),
    ]
