# Generated by Django 3.2.8 on 2021-11-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0008_auto_20211115_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(default='Pending', max_length=132, null=True),
        ),
    ]
