# Generated by Django 3.2.8 on 2021-11-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0009_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applicationlvl',
            field=models.CharField(default='HR', max_length=132, null=True),
        ),
    ]
