# Generated by Django 3.2.8 on 2021-11-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0010_jobapplication_applicationlvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='newjobapplication',
            name='General_Terms_Conditions',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='newjobapplication',
            name='Payment_terms',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='newjobapplication',
            name='Technical_Specifications',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='newjobapplication',
            name='Work_Flow',
            field=models.JSONField(null=True),
        ),
    ]
