# Generated by Django 3.2.8 on 2021-11-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0011_auto_20211122_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewJobsApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedBack', models.TextField(null=True)),
                ('freelancePlatformUrl', models.URLField(null=True)),
                ('applicationName', models.CharField(max_length=132)),
                ('status', models.CharField(max_length=132, null=True)),
                ('country', models.CharField(max_length=132, null=True)),
                ('username', models.CharField(max_length=132, null=True)),
                ('qualification', models.CharField(max_length=132, null=True)),
                ('freelancePlatform', models.CharField(max_length=132, null=True)),
                ('others', models.JSONField()),
                ('General_Terms_Conditions', models.JSONField()),
                ('Technical_Specifications', models.JSONField()),
                ('Payment_terms', models.JSONField()),
                ('Work_Flow', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='NewJobApplication',
        ),
    ]
