# Generated by Django 3.2.8 on 2021-12-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0012_auto_20211122_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=24, null=True)),
                ('download_speed', models.CharField(max_length=24, null=True)),
                ('upload_speed', models.CharField(max_length=24, null=True)),
            ],
        ),
    ]
