# Generated by Django 3.2.8 on 2021-12-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0014_alter_internetspeed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetspeed',
            name='user',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
