# Generated by Django 3.2.9 on 2021-11-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_jobapplication_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='userProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
