# Generated by Django 3.2.8 on 2021-11-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_jobapplication_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
