# Generated by Django 3.2.8 on 2021-11-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=132, null=True),
        ),
    ]
