# Generated by Django 3.2.8 on 2021-11-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='JobTitle',
            field=models.CharField(max_length=132, null=True),
        ),
    ]
